[package]
name = "tricktracktruck-planning-import"
version = "0.1.0"
authors = ["Logan Mzz <loganmzz@users.noreply.github.com>"]

[dependencies]
chrono = "0.4.0"
num = "0.1.40"

[dev-dependencies]
tricktracktruck_macros = { path = "macros" }
